on:
  - pull_request_review
  - pull_request_review_comment
  - issues
  - pull_request_target
  - issue_comment
  - gollum
  - discussion
  - discussion_comment

jobs:
  echo-chamber:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: echo '${{ toJSON(github.event.pages.*.title) }}'
